version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: user/app-node:v1.0.0
    container_name: node-app
    networks:
      - node-network
    ports:
      - "${PORT}:${PORT}"
    restart: always


networks:
  node-network:
   driver: bridge
