name: ci-boilerplate-node-javascript-workflow
on:
  pull_request:
    branches:
      - develop
      - homologation
      - main

jobs:
  check-application-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test

  check-application-homologation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test

  check-application-main:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test



