name: ci/cd-boilerplate-node-javascript-workflow
on:
  pull_request:
    branches:
      - develop
      - homologation
      - main

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying server on branch $GITHUB_HEAD_REF"


