name: ci/cd-boilerplate-node-javascript-workflow
on:
  pull_request:
    branches:
      - develop
      - homologation
      - main

jobs:
  deploy-develop:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy in [DEVELOP]
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test



