name: ci/cd-boilerplate-node-javascript-workflow
on: push

jobs:
  deploy-develop:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"


