name: ci/cd-boilerplate-node-javascript-workflow
on:
  pull_request:
    branches:
      - develop
      - homologation
      - main


jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - name: verify branch develop
        if: ${{ GITHUB_BASE_REF == 'develop' }}
        run: echo Deploy in [DEVELOP]
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
        run: npm ci
      - run: npm test



