name: ci/cd-boilerplate-node-javascript-workflow
on:
  pull_request:
    branches:
      - develop
      - homologation
      - main
env:
  GITHUB_BASE_REF: ${{ github.base_ref }}

jobs:
  deploy-develop:
    if: ${{ github.GITHUB_BASE_REF  == 'develop'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo GITHUB_BASE_REF
      - run: echo Deploy in [DEVELOP]
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test



